name: Spam detection

on:
  issue_comment:
    types: [created, edited]

jobs:
  detect-spam:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@main

      - name: Check for Spam
        uses: actions/github-script@v7
        with:
          script: |
            const comment = process.env.COMMENT_BODY
            const spam_words = ['Neuron Support Request']
            const comment_id = process.env.COMMENT_ID
            const owner = process.env.REPO_OWNER
            const repo = process.env.REPO_NAME
            if (spam_words.some(w => comment.includes(w))) {
              console.info(`Spam comment: ${comment}`)
              github.rest.issues.deleteComment({ owner, repo, comment_id })
            } else {
              console.info("No spam detected")
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          COMMENT_ID: ${{ github.event.comment.id }}
          REPO_OWNER: ${{github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}

